---
# - name: Host Surveey
#   hosts: localhost
#   gather_facts: no
#   tasks:
#     - add_host:
#       name: "{{ item }}"
#       group: alertmanager_hosts
#     with_items:
#       - '{{ survey_hosts.split(",") }}'
#       when: survey_hosts is defined and item != ''

- name: Install and set Alertmanager
  hosts: alertmanager_hosts
  gather_facts: no
  vars:
    - ansible_python_interpeter: /usr/bin/python3
    - am_version: 0.27.0
    - alertmanager_url_sufix: /alerts
    - nginx_add: |
        # Ansible Added AlertManager Location
                location {{ alertmanager_url_sufix }} {  # http://{{ inventory_hostname }}:443{{ alertmanager_url_sufix }}/#/alerts
                    rewrite ^{{ alertmanager_url_sufix }}(.*)$ $1 break;
                    proxy_pass http://{{inventory_hostname}}:9093
                }

  tasks:
    - name: Create Directory
      file:
        path: /etc/prometheus
        state: directory

    - name: Unarchive AlertManager
      unarchive:
        src: "files/alertmanager-{{ am_version }}.linux-amd64.tar.gz"
        dest: /etc/prometheus/
    
    - name: Copy AlertManager Service
      template:
        src: templates/alertmanager.service.js
        dest: /etc/systemd/system/alertmanager.service

    - name: Start and enable Alertmanager
      systemd:
        name: alertmanager
        daemon_reload: yes
        enabled: yes
        state: started

    - name: set nginx
      include_role:
        name: set_nginx

    - name: Check If Alertmanager in Nginx
      shell: grep ' {{ alertmanager_url_sufix }} {' /etc/nginx/nginx.conf
      register: am_in_nginx
      failed_when: am_in_nginx.rc == 2000

    - name: Add Alertmanager to Nginx
      blockinfile:
        path: /etc/nginx/nginx.conf
        marker: " "
        inserafter: '^        include \/etc\/nginx\/default\.d\/\*\.conf\;$'
        block: "{{ nginx_add }}"
        state: present
      register: add_nginx
      when: am_in_nginx.rc == 1

    - name: reload nginx
      include_role:
        name: reload_nginx
