global:
  scrape_intervel: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    project: prometheus

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_comfigs:
      - targets:
        - ""

# Load rules once and peeiodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert.rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config

  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    file_sd_configs:
      - files:
          - "targers.json"
    relable_configs:
      - source_labels: [__address__]
        target_labels: instance
        regex: '(.+):9100'
        replacement: '${1}'
        action: replace
